name: main
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      - name: Checkout code
        uses: actions/checkout@master

      - name: run tests
        run: |
          go test -coverprofile=coverage.txt -covermode=atomic ./...       

      - name: Publish coverage
        uses: codecov/codecov-action@v1.0.6
        with:
          token: ${{secrets.CODECOV_TOKEN}}
          file: ./coverage.txt
